---
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- gem install bundler --pre --no-rdoc --no-ri
- ruby gemfiles/minitest_tu_shim.rb
- rake travis:before -t
language: ruby
notifications:
  email:
  - mike@blowmage.com
rvm:
- 1.9.3
- ruby-head
gemfile:
- gemfiles/3.0.gemfile
- gemfiles/3.1.gemfile
- gemfiles/3.2.gemfile
- gemfiles/4.0.gemfile
script: rake travis
