---
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- ruby gemfiles/minitest_tu_shim.rb
- rake travis:before -t
language: ruby
notifications:
  email:
  - mike@blowmage.com
rvm:
- 1.9.3
- 1.9.2
- jruby-18mode
- jruby-19mode
- rbx-18mode
- rbx-19mode
- ruby-head
- jruby-head
- 1.8.7
- ree
gemfile:
- gemfiles/3.0.gemfile
- gemfiles/3.1.gemfile
- gemfiles/3.2.gemfile
script: rake travis
